// Sprint 2 — serialize a chapter's full data surface into a SQL migration that
// upserts chapter_content (the server-side store behind the get-chapter Edge
// Function). Run from the repo root with:
//   npx tsx scripts/export-chapter-content.ts
//
// Regenerate + `supabase db push` whenever ch2 content changes (until the
// Sprint 4 admin upload flow replaces this).
import { writeFileSync } from 'node:fs'
import { deepStrictEqual } from 'node:assert'

import { chapter2 } from '../src/data/ch2/chapter2'
import { ch2KeyDates } from '../src/data/ch2/keyDates'
import { ch2Vocabulary } from '../src/data/ch2/vocabulary'
import { ch2Sources } from '../src/data/ch2/sources'
import { ch2KeyPeople } from '../src/data/ch2/keyPeople'
import { ch2Flashcards } from '../src/data/ch2/flashcards'
import { ch2Figures } from '../src/data/ch2/figures'
import { ch2MapDefinitions } from '../src/data/ch2/maps'
import {
  ch2McqActivities,
  ch2FillBlankActivities,
  ch2TrueFalseActivities,
} from '../src/data/ch2/activities/quizActivities'
import { ch2MatchActivities } from '../src/data/ch2/activities/matchActivities'
import { ch2NcertQuestions } from '../src/data/ch2/activities/ncertQuestions'
import {
  ch2MapIdentifyActivities,
  ch2MapLabelActivities,
} from '../src/data/ch2/activities/mapActivities'

const CHAPTER_KEY = 'c10-hist-ch2'

const bundle = {
  chapter: chapter2,
  keyDates: ch2KeyDates,
  vocabulary: ch2Vocabulary,
  sources: ch2Sources,
  keyPeople: ch2KeyPeople,
  flashcards: ch2Flashcards,
  figures: ch2Figures,
  mapDefinitions: ch2MapDefinitions,
  activities: {
    mcq: ch2McqActivities,
    fillBlank: ch2FillBlankActivities,
    trueFalse: ch2TrueFalseActivities,
    match: ch2MatchActivities,
    timeline: [],
    ncert: ch2NcertQuestions,
    mapIdentify: ch2MapIdentifyActivities,
    mapLabel: ch2MapLabelActivities,
  },
}

// Guard: the bundle must survive JSON round-tripping unchanged (functions,
// Dates or undefined values in the data would silently corrupt it).
const json = JSON.stringify(bundle)
deepStrictEqual(JSON.parse(json), bundle, 'chapter bundle is not JSON-pure')

const escaped = json.replace(/'/g, "''")
const sql = `-- GENERATED by scripts/export-chapter-content.ts — do not edit by hand.
-- Upserts the Chapter 2 content bundle into chapter_content.
insert into chapter_content (chapter_id, content, updated_at)
values ('${CHAPTER_KEY}', '${escaped}'::jsonb, now())
on conflict (chapter_id)
do update set content = excluded.content, updated_at = now();
`

const stamp = new Date()
  .toISOString()
  .replace(/[-:T]/g, '')
  .slice(0, 14)
const path = `supabase/migrations/${stamp}_ch2_content_data.sql`
writeFileSync(path, sql)
console.log(`Wrote ${path} (${(sql.length / 1024).toFixed(0)} KB, ` +
  `${bundle.chapter.sections.length} sections, ${bundle.figures.length} figures, ` +
  `${bundle.flashcards.length} flashcards)`)
