// Serialize authored papers (content-src/papers/*.txt, PAPER_AUTHORING_GUIDE
// format) into a SQL seed migration for the Sprint 4 test-engine tables.
// Neha's papers go through the admin Papers tab; this script exists so
// repo-authored seed papers ride the same parser and migrations pipeline.
//
// Run from the repo root:
//   npx tsx scripts/export-paper.ts
// then `supabase db push`.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { parsePaper } from '../src/lib/paperFormat'

const PAPERS_DIR = 'content-src/papers'
const MIGRATION = 'supabase/migrations/20260718110000_seed_papers.sql'
const TAG = '$paper_seed$'

function q(value: string): string {
  if (value.includes('paper_seed')) throw new Error('content collides with dollar-quote tag')
  return `${TAG}${value}${TAG}`
}

function qOrNull(value: string | null | undefined): string {
  return value == null ? 'null' : q(value)
}

const files = readdirSync(PAPERS_DIR).filter((f) => f.endsWith('.txt')).sort()
if (!files.length) {
  console.error(`No .txt papers found in ${PAPERS_DIR}`)
  process.exit(1)
}

const parts: string[] = [
  '-- GENERATED by scripts/export-paper.ts — do not edit by hand.',
  '-- Seed papers authored in content-src/papers/ (PAPER_AUTHORING_GUIDE format).',
  '-- Seeded papers are published immediately (repo-reviewed content).',
  '',
]

for (const file of files) {
  const text = readFileSync(join(PAPERS_DIR, file), 'utf8')
  const { paper, errors, warnings } = parsePaper(text)
  for (const w of warnings) console.warn(`[warn] ${file}: ${w}`)
  if (!paper) {
    console.error(`[FAIL] ${file}:`)
    for (const e of errors) console.error(`  - ${e}`)
    process.exit(1)
  }

  const totalMarks = paper.questions.reduce((s, x) => s + x.marks, 0)
  const objectiveMarks = paper.questions
    .filter((x) => x.qtype === 'mcq')
    .reduce((s, x) => s + x.marks, 0)

  parts.push(`-- ${paper.id}: ${paper.title} (${totalMarks} marks, ${paper.questions.length} questions)`)
  parts.push(
    `insert into papers (id, chapter_id, title, description, total_marks, objective_marks, question_count, duration_minutes, position, status)
values (${q(paper.id)}, ${q(paper.chapter_id)}, ${q(paper.title)}, ${qOrNull(paper.description)}, ${totalMarks}, ${objectiveMarks}, ${paper.questions.length}, ${paper.duration_minutes}, ${paper.position ?? 1}, 'published')
on conflict (id) do update set
  chapter_id = excluded.chapter_id,
  title = excluded.title,
  description = excluded.description,
  total_marks = excluded.total_marks,
  objective_marks = excluded.objective_marks,
  question_count = excluded.question_count,
  duration_minutes = excluded.duration_minutes,
  position = excluded.position,
  updated_at = now();`,
  )
  parts.push(`delete from questions where paper_id = ${q(paper.id)};`)
  parts.push(`delete from paper_sources where paper_id = ${q(paper.id)};`)

  for (const s of paper.sources) {
    parts.push(
      `insert into paper_sources (paper_id, source_id, title, body)
values (${q(paper.id)}, ${q(s.source_id)}, ${qOrNull(s.title)}, ${q(s.body)});`,
    )
  }

  paper.questions.forEach((qn, i) => {
    parts.push(
      `insert into questions (paper_id, position, section_label, qtype, marks, prompt, source_id, options, correct_index, scheme)
values (${q(paper.id)}, ${i + 1}, ${q(qn.section_label)}, ${q(qn.qtype)}, ${qn.marks}, ${q(qn.prompt)}, ${qOrNull(qn.source_id)}, ${
        qn.options ? `${q(JSON.stringify(qn.options))}::jsonb` : 'null'
      }, ${qn.correct_index ?? 'null'}, ${qn.scheme ? `${q(JSON.stringify(qn.scheme))}::jsonb` : 'null'});`,
    )
  })
  parts.push('')
  console.log(
    `[ok] ${file} → ${paper.id}: ${paper.questions.length} questions, ${totalMarks} marks (${objectiveMarks} objective), ${paper.sources.length} sources`,
  )
}

writeFileSync(MIGRATION, parts.join('\n\n'))
console.log(`\nWrote ${MIGRATION}`)
